services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: ../docker/Frontend.Dockerfile
    ports:
      - "80:80"
    environment:
      APP_ENV_PREFIX: VIRGO_
      VIRGO_API_URL: http://localhost:8080
    depends_on:
      - backend

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ../docker/Backend.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: